---
- hosts: mesos-masters

  tasks:
    - name: Setup Mesos master

    - apt-key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: E56151BF

    - apt_repository:
        repo: deb http://ftp.de.debian.org/debian jessie-backports main contrib non-free
        state: present

    - apt_repository:
        repo: deb http://repos.mesosphere.com/debian jessie main
        state: present

    - apt:
        update_cache: yes
        upgrade: yes

    - apt:
        name: openjdk-8-jre
        default_release: jessie-backports

    - name: Install list of packages
        apt: name={{item}} state=installed
        with_items:
             - vim
             - byobu
             - curl
             - wget
             - rsync
             - ranger
             - zsh
             - git
             - sed
             - htop


cd /root && git clone https://github.com/robbyrussell/oh-my-zsh .oh-my-zsh
cp /vagrant/common-files/zshrc /root/.zshrc
chsh -s /bin/zsh

# Change root password
echo root:azerty | chpasswd

##
## INSTALL MESOS
##

# Install Mesos and frameworks
apt-get install -y mesos marathon chronos
apt-get install -y zookeeper zookeeperd
apt-get install -y haproxy haproxy-doc

# Install Docker
curl -fsSL get.docker.com | sh

# Add docker group to vagrant user
usermod -aG docker vagrant

# install python pip and update it
apt-get install -y python-pip -t jessie-backports
pip install pip --upgrade

# install mesos cli and docker compose
pip install docker-compose
pip install mesos.cli

# Add startup script (TODO: use System V)
cp /vagrant/master-files/rc.local /etc/rc.local
chmod +x /etc/rc.local

# Enable haproxy / marathon bridge for load balancing
/vagrant/common-files/haproxy-marathon-bridge install_haproxy_system localhost:8080

# Set ip of the slave. Slave or master should choice a bad interface like loopback
# and only have routable addresses to avoid issues
echo "${MASTER_ADDRESS}" | sudo tee /etc/mesos-master/ip
echo "${MASTER_HOST_NAME}" | sudo tee /etc/mesos-slave/ip

# Register zookeeper master url for slave
echo "zk://${MASTER_ADDRESS}:2181/mesos" | sudo tee /etc/mesos/zk

# Register a human readable namefor cluster
echo "Jessie-Cluster" | sudo tee /etc/mesos-master/cluster

# Enable Mesos support for Docker
echo "docker,mesos" | sudo tee /etc/mesos-slave/containerizers
echo "8mins" | sudo tee /etc/mesos-slave/executor_registration_timeout

# Add entry to /etc/hosts for slave
echo -e "#{SLAVE1_ADDRESS} #{SLAVE1_HOSTNAME}\n" >> /etc/hosts
echo -e "#{SLAVE2_ADDRESS} #{SLAVE2_HOSTNAME}\n" >> /etc/hosts
echo -e "#{SLAVE3_ADDRESS} #{SLAVE3_HOSTNAME}\n" >> /etc/hosts

# First startup
/etc/rc.local